# Generated by Django 6.0 on 2025-12-16 03:04

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteCrimen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion', django.contrib.gis.db.models.fields.PointField(help_text='Latitud y Longitud del incidente', srid=4326)),
                ('tipo_crimen', models.CharField(choices=[('robo', 'Robo a una persona'), ('asalto', 'Asalto a Domicilio / Negocio'), ('secuestro', 'Secuestro'), ('extorsion', 'Extorsión'), ('asesinato', 'Asesinato/Homicidio'), ('otro', 'Otro Incidente')], default='robo', max_length=50)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora del reporte')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del incidente', null=True)),
                ('ciudad', models.CharField(help_text='Ciudad o Sector del Incidente', max_length=100)),
                ('estado_verificacion', models.CharField(choices=[('pendiente', 'Pendiente/En Proceso'), ('verificado', 'Verificado'), ('falso', 'Falso')], default='pendiente', max_length=20)),
            ],
            options={
                'verbose_name': 'Reporte de Crimen',
                'verbose_name_plural': 'Reporte de Crimenes',
                'indexes': [models.Index(fields=['ubicacion'], name='api_reporte_ubicaci_8daf58_idx')],
            },
        ),
    ]
